### ISSUE TITLE
Tracker counter does not work when using Classic Theme Restorer

### ISSUE THREAD

**Issue by jeberger** [EFForg/privacybadgerchrome#355]
When using Classic Theme Restorer, the counter tracker appears as white on a transparent (→ light grey) background. This is because CTR includes the following CSS rule which overrides privacy badger's inline styles:

```css
#nav-bar toolbarbutton .toolbarbutton-badge,
#nav-bar toolbarbutton .toolbarbutton-badge-container {
  background: none !important;
}
```

I think privacy badger should use extra CSS classes instead of inline styles to set the red or green background on the counter. This way, we could have the proper background through the use of appropriate stylesheets like:

```css
#nav-bar toolbarbutton .toolbarbutton-badge.counter_red {
  background-color: red !important;
}
#nav-bar toolbarbutton .toolbarbutton-badge.counter_green {
  background-color: green !important;
}
```
